const catalogo = [
  { brand:"821 Argento", variante:"KS 20", codice_aams:"7", alias:["821 argento","ottoventuno argento"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"821 Blu", variante:"KS 20", codice_aams:"66", alias:["821 blu","ottoventuno blu"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"821 Rossa", variante:"KS 20", codice_aams:"2771", alias:["821 rossa","ottoventuno rossa"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"American Spirit Blue", variante:"KS 20", codice_aams:"1942", alias:["american spirit blu","american spirit blue","spirit blu"], prezzo_pacchetto:6.20, peso_stecca_g:215, pezzi_per_stecca:10 },
  { brand:"American Spirit Yellow", variante:"KS 20", codice_aams:"1943", alias:["american spirit yellow","american spirit gialle","spirit gialle"], prezzo_pacchetto:6.50, peso_stecca_g:215, pezzi_per_stecca:10 },
  { brand:"American Spirit Orange", variante:"KS 20", codice_aams:"2231", alias:["american spirit orange","american spirit arancione"], prezzo_pacchetto:6.50, peso_stecca_g:215, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges Gold", variante:"KS 20", codice_aams:"550", alias:["benson hedges gold","benson gold","b&h gold","benson","bh gold"], prezzo_pacchetto:6.50, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges Blue", variante:"KS 20", codice_aams:"2982", alias:["benson hedges blu","benson blu","b&h blue","bh blu"], prezzo_pacchetto:5.30, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges Blue", variante:"Soft 20", codice_aams:"3118", alias:["benson hedges blu morbide","benson blu cartoccio","bh blu morbide"], prezzo_pacchetto:5.30, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges Red", variante:"KS 20", codice_aams:"2981", alias:["benson hedges rosse","benson rosse","b&h red","bh rosse"], prezzo_pacchetto:5.30, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges Red", variante:"Soft 20", codice_aams:"3117", alias:["benson hedges rosse morbide","benson rosse cartoccio"], prezzo_pacchetto:5.30, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges White", variante:"KS 20", codice_aams:"3016", alias:["benson hedges white","benson bianche","b&h white"], prezzo_pacchetto:5.30, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Benson & Hedges Yellow", variante:"KS 20", codice_aams:"3015", alias:["benson hedges yellow","benson gialle","b&h yellow"], prezzo_pacchetto:5.30, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Camel Yellow", variante:"KS 20", codice_aams:"264", alias:["camel gialle","camel yellow","camel classiche","cammel gialle"], prezzo_pacchetto:6.30, peso_stecca_g:215, pezzi_per_stecca:10 },
  { brand:"Camel Yellow", variante:"Soft 20", codice_aams:"270", alias:["camel gialle morbide","camel yellow cartoccio","camel gialle soft"], prezzo_pacchetto:5.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Camel Yellow 100s", variante:"100s 20", codice_aams:"405", alias:["camel yellow 100","camel gialle lunghe"], prezzo_pacchetto:6.30, peso_stecca_g:220, pezzi_per_stecca:10 },
  { brand:"Camel Blue", variante:"KS 20", codice_aams:"478", alias:["camel blu","camel blue","cammel blu","camel light"], prezzo_pacchetto:6.30, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Camel Blue", variante:"Soft 20", codice_aams:"632", alias:["camel blu morbide","camel blue cartoccio","camel blu soft"], prezzo_pacchetto:5.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Camel Blue 100s", variante:"100s 20", codice_aams:"546", alias:["camel blue 100","camel blu lunghe"], prezzo_pacchetto:6.30, peso_stecca_g:220, pezzi_per_stecca:10 },
  { brand:"Camel Orange", variante:"KS 20", codice_aams:"464", alias:["camel orange","camel arancione"], prezzo_pacchetto:6.30, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Camel Silver", variante:"KS 20", codice_aams:"552", alias:["camel silver","camel argento"], prezzo_pacchetto:6.30, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Camel White", variante:"KS 20", codice_aams:"2108", alias:["camel white","camel bianche"], prezzo_pacchetto:6.30, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Camel Activate", variante:"KS 20", codice_aams:"20225", alias:["camel activate","camel activ","camel mentol","camel con la pallina","camel menta"], prezzo_pacchetto:6.30, peso_stecca_g:215, pezzi_per_stecca:10 },
  { brand:"Camel Compact", variante:"KS 20", codice_aams:"20462", alias:["camel compact","camel compatte"], prezzo_pacchetto:5.70, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Camel Essential Blue", variante:"KS 20", codice_aams:"2240", alias:["camel essential","camel essential blue","camel essential blu"], prezzo_pacchetto:5.70, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Chesterfield Blue KS", variante:"KS 20", codice_aams:"201", alias:["chestefild blu","chesterfield blu","chester blue","chester blu","chesterfild blue"], prezzo_pacchetto:5.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Chesterfield Blue KS", variante:"Soft 20", codice_aams:"2082", alias:["chesterfield blu morbide","chester blu cartoccio","chestefild blu soft"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Chesterfield Blue 100", variante:"100s 20", codice_aams:"3114", alias:["chesterfield blue 100","chester blu 100","chester blu lunghe"], prezzo_pacchetto:5.80, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Chesterfield Original KS", variante:"KS 20", codice_aams:"96", alias:["chestefild rosse","chesterfield rosse","chester rosse","chesterfield original","chester original"], prezzo_pacchetto:5.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Chesterfield Original KS", variante:"Soft 20", codice_aams:"2081", alias:["chesterfield rosse morbide","chester rosse cartoccio","chestefild rosse soft"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Chesterfield Original 100", variante:"100s 20", codice_aams:"3113", alias:["chesterfield original 100","chester rosse 100"], prezzo_pacchetto:5.80, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Chesterfield Silver KS", variante:"KS 20", codice_aams:"2257", alias:["chester silver","chesterfield silver","chestefild silver"], prezzo_pacchetto:5.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Chesterfield Label Blue KS", variante:"KS 20", codice_aams:"21419", alias:["chesterfield label blue","chester label blu"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Chesterfield Label Original KS", variante:"KS 20", codice_aams:"21420", alias:["chesterfield label original","chester label originale"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Davidoff Classic", variante:"KS 20", codice_aams:"728", alias:["davidoff classic","davidof classic","davidoff classiche"], prezzo_pacchetto:6.80, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Davidoff Gold", variante:"KS 20", codice_aams:"758", alias:["davidoff gold","davidof gold","davidoff oro"], prezzo_pacchetto:6.80, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Davidoff Blue", variante:"KS 20", codice_aams:"3157", alias:["davidoff blue","davidof blu","davidoff blu"], prezzo_pacchetto:5.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Diana Blu KS", variante:"KS 20", codice_aams:"630", alias:["diana blu","diana blue","diana azzurra"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Diana Blu KS", variante:"Soft 20", codice_aams:"406", alias:["diana blu morbide","diana blu cartoccio","diana blue soft"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Diana Blu 100s", variante:"100s 20", codice_aams:"1983", alias:["diana blu 100","diana blu lunghe"], prezzo_pacchetto:5.50, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Diana Rossa KS", variante:"KS 20", codice_aams:"233", alias:["diana rosse","diana red","diana rosso","diana rossa"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Diana Rossa KS", variante:"Soft 20", codice_aams:"234", alias:["diana rosse morbide","diana rossa cartoccio","diana rosse soft"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Diana Rossa 100s", variante:"100s 20", codice_aams:"1982", alias:["diana rosse 100","diana rosse lunghe"], prezzo_pacchetto:5.50, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Dunhill International", variante:"KS 20", codice_aams:"549", alias:["dunhill international","dunhil international"], prezzo_pacchetto:7.00, peso_stecca_g:215, pezzi_per_stecca:10 },
  { brand:"Dunhill Gold", variante:"KS 20", codice_aams:"291", alias:["dunhill gold","dunhil gold"], prezzo_pacchetto:6.50, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Dunhill Blue", variante:"KS 20", codice_aams:"818", alias:["dunhill blue","dunhil blu","dunhill blu"], prezzo_pacchetto:6.50, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Dunhill MS Rosse", variante:"KS 20", codice_aams:"993", alias:["dunhill ms rosse","ms rosse dunhill"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Dunhill MS Rosse", variante:"Soft 20", codice_aams:"852", alias:["dunhill ms rosse morbide","ms rosse dunhill cartoccio"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Dunhill MS Bionde", variante:"KS 20", codice_aams:"177", alias:["dunhill ms bionde","ms bionde dunhill"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Dunhill MS Bionde", variante:"Soft 20", codice_aams:"176", alias:["dunhill ms bionde morbide","ms bionde dunhill cartoccio"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Dunhill MS Chiare", variante:"KS 20", codice_aams:"851", alias:["dunhill ms chiare","ms chiare dunhill"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Dunhill MS Bianche", variante:"KS 20", codice_aams:"857", alias:["dunhill ms bianche","ms bianche dunhill"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Elixyr Red", variante:"KS 20", codice_aams:"1480", alias:["elixyr red","elixir red","elixyr rosse","elixir rosse"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Elixyr Blue", variante:"KS 20", codice_aams:"1481", alias:["elixyr blue","elixir blue","elixyr blu","elixir blu"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Elixyr+", variante:"KS 20", codice_aams:"1719", alias:["elixyr plus","elixir plus","elixyr+"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Gauloises Blondes Blu", variante:"KS 20", codice_aams:"558", alias:["gauloises blu","gauloises blondes blue","gauloise blu","galois blu"], prezzo_pacchetto:5.50, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Gauloises Blondes Rossa", variante:"KS 20", codice_aams:"640", alias:["gauloises rosse","gauloises blondes red","gauloise rosse","galois rosse"], prezzo_pacchetto:5.50, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Gauloises Blondes Gialla", variante:"KS 20", codice_aams:"477", alias:["gauloises gialle","gauloises blondes yellow","gauloise gialle"], prezzo_pacchetto:5.20, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"JPS Original", variante:"KS 20", codice_aams:"154", alias:["jps original","jps","jps classiche"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"JPS Red", variante:"KS 20", codice_aams:"293", alias:["jps red","jps rosse"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"JPS Red", variante:"Soft 20", codice_aams:"2957", alias:["jps red morbide","jps rosse cartoccio","jps rosse soft"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"JPS Blue Stream", variante:"KS 20", codice_aams:"2286", alias:["jps blue","jps blu","jps blue stream"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"JPS Blue", variante:"Soft 20", codice_aams:"2956", alias:["jps blue morbide","jps blu cartoccio"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"JPS Silver", variante:"KS 20", codice_aams:"300", alias:["jps silver","jps argento"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"JPS White", variante:"KS 20", codice_aams:"3941", alias:["jps white","jps bianche"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Kent Blue", variante:"KS 20", codice_aams:"891", alias:["kent blue","kent blu"], prezzo_pacchetto:6.50, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Kent Surround", variante:"KS 20", codice_aams:"499", alias:["kent surround","kent"], prezzo_pacchetto:6.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"L&M Blue Label", variante:"KS 20", codice_aams:"1303", alias:["l&m blue","l&m blu","lm blue","lm blu","l e m blu"], prezzo_pacchetto:5.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"L&M Red Label", variante:"KS 20", codice_aams:"1313", alias:["l&m red","l&m rosse","lm red","lm rosse","l e m rosse"], prezzo_pacchetto:5.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Lucky Strike Original", variante:"KS 20", codice_aams:"451", alias:["lucky strike","lucky rosse","laki strike","lucky classiche","lucky originale"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Lucky Strike Original", variante:"Soft 20", codice_aams:"536", alias:["lucky strike morbide","lucky original cartoccio","lucky strike soft"], prezzo_pacchetto:5.30, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Lucky Strike Amber", variante:"KS 20", codice_aams:"867", alias:["lucky amber","lucky strike amber","laki amber","lucky gialle","lucky dorate"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Lucky Strike Silver Bay", variante:"KS 20", codice_aams:"3319", alias:["lucky silver","lucky silver bay","lucky argento"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Marlboro Gold KS", variante:"KS 20", codice_aams:"8001185", alias:["malboro gold","marbolo gold","marlboro gold","marlboro dorata","malboro dorata"], prezzo_pacchetto:6.80, peso_stecca_g:220, pezzi_per_stecca:10 },
  { brand:"Marlboro Rosse KS", variante:"KS 20", codice_aams:"8001180", alias:["malboro rosse","marbolo rosse","marlboro red","malboro red","marlboro rosso"], prezzo_pacchetto:6.80, peso_stecca_g:220, pezzi_per_stecca:10 },
  { brand:"Marlboro White KS", variante:"KS 20", codice_aams:"8001188", alias:["malboro white","marlboro bianche","malboro bianca"], prezzo_pacchetto:6.80, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Marlboro Silver KS", variante:"KS 20", codice_aams:"8001190", alias:["malboro silver","marlboro silver","malboro argento"], prezzo_pacchetto:6.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Marlboro Touch KS", variante:"KS 20", codice_aams:"8001192", alias:["malboro touch","marlboro touch"], prezzo_pacchetto:6.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Marlboro Gold Pocket Pack", variante:"KS 10", codice_aams:"8001186", alias:["malboro gold pocket","marlboro pocket","malboro piccola","marlboro da 10"], prezzo_pacchetto:3.50, peso_stecca_g:120, pezzi_per_stecca:10 },
  { brand:"Merit KS", variante:"KS 20", codice_aams:"8012050", alias:["merit","merit gialle","merit ks","merit classiche"], prezzo_pacchetto:6.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Merit Bay", variante:"KS 20", codice_aams:"8012055", alias:["merit bay","merit blu","merit bay blue"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"MS Rosse", variante:"KS 20", codice_aams:"8008010", alias:["emesse rosse","ms rosse","nazionali rosse","nazionale rosse","ms classic"], prezzo_pacchetto:5.50, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"MS Blu", variante:"KS 20", codice_aams:"8008011", alias:["emesse blu","ms blu","nazionali blu","nazionale blu","ms azzurre"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"MS Chiare", variante:"KS 20", codice_aams:"8008012", alias:["emesse chiare","ms chiare","nazionali chiare"], prezzo_pacchetto:5.40, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"MS Bionde", variante:"KS 20", codice_aams:"8008013", alias:["emesse bionde","ms bionde","nazionali bionde"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Muratti Ambassador", variante:"KS 20", codice_aams:"8016010", alias:["muratti","muratti ambassador","murati"], prezzo_pacchetto:6.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Muratti Silver", variante:"SSL 20", codice_aams:"8016011", alias:["muratti silver","muratti argento","murati silver"], prezzo_pacchetto:6.80, peso_stecca_g:185, pezzi_per_stecca:10 },
  { brand:"Pall Mall Blue", variante:"KS 20", codice_aams:"8007123", alias:["pall mall blu","pallmall blue","pal mal blu","pall mall light"], prezzo_pacchetto:5.30, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Pall Mall Red", variante:"KS 20", codice_aams:"8007120", alias:["pall mall rosse","pallmall red","pal mal rosse","pall mall rosso"], prezzo_pacchetto:5.30, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Peter Stuyvesant Original", variante:"KS 20", codice_aams:"8018010", alias:["peter stuyvesant","peter stuyvesant original","pietr stuyvesant","peter classiche"], prezzo_pacchetto:6.30, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Peter Stuyvesant Gold", variante:"KS 20", codice_aams:"8018011", alias:["peter stuyvesant gold","peter gold"], prezzo_pacchetto:6.00, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Philip Morris Red", variante:"KS 20", codice_aams:"8005111", alias:["philip morris rosse","filippo morris rosse","filip morris red","pm rosse","filtrini","pm red"], prezzo_pacchetto:5.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Philip Morris Blue", variante:"KS 20", codice_aams:"8005110", alias:["philip morris blu","filippo morris blu","filip morris blue","pm blue","pm blu","filtrini blu"], prezzo_pacchetto:5.50, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Philip Morris Azure", variante:"KS 20", codice_aams:"8005115", alias:["philip morris azure","pm azure","philip morris azzurre"], prezzo_pacchetto:5.50, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Pueblo Classic", variante:"KS 20", codice_aams:"8013010", alias:["pueblo classic","pueblo classiche","pueblo rosse"], prezzo_pacchetto:6.00, peso_stecca_g:210, pezzi_per_stecca:10 },
  { brand:"Pueblo Blue", variante:"KS 20", codice_aams:"8013011", alias:["pueblo blue","pueblo blu","pueblo azzurre"], prezzo_pacchetto:6.00, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Pueblo Orange", variante:"KS 20", codice_aams:"8013012", alias:["pueblo orange","pueblo arancione"], prezzo_pacchetto:6.00, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Rothmans Blue", variante:"KS 20", codice_aams:"8010234", alias:["rothmans blu","rothman blue","rotman blu","rothmans"], prezzo_pacchetto:5.30, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Rothmans Red", variante:"KS 20", codice_aams:"8010230", alias:["rothmans rosse","rothman red","rotman rosse"], prezzo_pacchetto:5.30, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Vogue Lilas", variante:"SSL 20", codice_aams:"8019010", alias:["vogue lilas","vogue lilla","vogue viola"], prezzo_pacchetto:6.00, peso_stecca_g:185, pezzi_per_stecca:10 },
  { brand:"Vogue Bleue", variante:"SSL 20", codice_aams:"8019011", alias:["vogue bleue","vogue blu","vogue blue"], prezzo_pacchetto:6.00, peso_stecca_g:185, pezzi_per_stecca:10 },
  { brand:"West Original", variante:"KS 20", codice_aams:"8020210", alias:["west original","west rosse","west classiche"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"West Silver", variante:"KS 20", codice_aams:"8020211", alias:["west silver","west argento","west bianche"], prezzo_pacchetto:5.20, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Winston Red", variante:"KS 20", codice_aams:"8003567", alias:["winston rosse","winston red","vinston rosse","wiston red","uinston rosse"], prezzo_pacchetto:5.80, peso_stecca_g:205, pezzi_per_stecca:10 },
  { brand:"Winston Blue", variante:"KS 20", codice_aams:"8003568", alias:["winston blu","winston blue","vinston blu","wiston blue","uinston blu"], prezzo_pacchetto:5.80, peso_stecca_g:200, pezzi_per_stecca:10 },
  { brand:"Winston Silver", variante:"KS 20", codice_aams:"8003570", alias:["winston silver","winston argento","vinston silver"], prezzo_pacchetto:5.80, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Winston White", variante:"KS 20", codice_aams:"8003572", alias:["winston white","winston bianche","winston bianco"], prezzo_pacchetto:5.80, peso_stecca_g:195, pezzi_per_stecca:10 },
  { brand:"Toscanello", variante:"Conf. 5", codice_aams:"8015010", alias:["toscanello","toscanelli","toscano","toscanelo","toscanetti"], prezzo_pacchetto:4.20, peso_stecca_g:85, pezzi_per_stecca:10 },
  { brand:"Toscanello Aroma Caffe", variante:"Conf. 5", codice_aams:"8015011", alias:["toscanello caffe","toscanelli caffe","toscano caffe"], prezzo_pacchetto:4.50, peso_stecca_g:85, pezzi_per_stecca:10 },
  { brand:"Toscanello Aroma Vaniglia", variante:"Conf. 5", codice_aams:"8015012", alias:["toscanello vaniglia","toscanelli vaniglia"], prezzo_pacchetto:4.50, peso_stecca_g:85, pezzi_per_stecca:10 },
  { brand:"Toscanello Aroma Grappa", variante:"Conf. 5", codice_aams:"8015013", alias:["toscanello grappa","toscanelli grappa"], prezzo_pacchetto:4.50, peso_stecca_g:85, pezzi_per_stecca:10 },
  { brand:"HEETS Amber", variante:"Pack 20", codice_aams:"8020100", alias:["heets amber","iqos amber","hites amber","hits amber"], prezzo_pacchetto:5.50, peso_stecca_g:55, pezzi_per_stecca:10 },
  { brand:"HEETS Yellow", variante:"Pack 20", codice_aams:"8020101", alias:["heets yellow","iqos yellow","hites yellow","heets gialle"], prezzo_pacchetto:5.50, peso_stecca_g:55, pezzi_per_stecca:10 },
  { brand:"HEETS Turquoise", variante:"Pack 20", codice_aams:"8020102", alias:["heets turchese","heets turquoise","iqos turchese","hites verdi"], prezzo_pacchetto:5.50, peso_stecca_g:55, pezzi_per_stecca:10 },
  { brand:"HEETS Bronze", variante:"Pack 20", codice_aams:"8020105", alias:["heets bronze","heets bronzo","iqos bronze"], prezzo_pacchetto:5.50, peso_stecca_g:55, pezzi_per_stecca:10 },
  { brand:"HEETS Silver", variante:"Pack 20", codice_aams:"8020106", alias:["heets silver","heets argento","iqos silver"], prezzo_pacchetto:5.50, peso_stecca_g:55, pezzi_per_stecca:10 },
  { brand:"TEREA Amber", variante:"Pack 20", codice_aams:"8021100", alias:["terea amber","teria amber","iqos iluma amber","terea gialle"], prezzo_pacchetto:5.50, peso_stecca_g:50, pezzi_per_stecca:10 },
  { brand:"TEREA Yellow", variante:"Pack 20", codice_aams:"8021101", alias:["terea yellow","teria yellow","iqos iluma yellow","terea giallo"], prezzo_pacchetto:5.50, peso_stecca_g:50, pezzi_per_stecca:10 },
  { brand:"TEREA Turquoise", variante:"Pack 20", codice_aams:"8021103", alias:["terea turchese","teria turquoise","iqos iluma turchese"], prezzo_pacchetto:5.50, peso_stecca_g:50, pezzi_per_stecca:10 },
  { brand:"TEREA Bronze", variante:"Pack 20", codice_aams:"8021104", alias:["terea bronze","teria bronze","iqos iluma bronze"], prezzo_pacchetto:5.50, peso_stecca_g:50, pezzi_per_stecca:10 },
  { brand:"TEREA Silver", variante:"Pack 20", codice_aams:"8021105", alias:["terea silver","teria silver","iqos iluma silver"], prezzo_pacchetto:5.50, peso_stecca_g:50, pezzi_per_stecca:10 },
  { brand:"GLO Neo Classic", variante:"Pack 20", codice_aams:"8022050", alias:["glo neo","glo classic","neo tobacco","glo tabacco","glo classiche"], prezzo_pacchetto:4.30, peso_stecca_g:45, pezzi_per_stecca:10 },
  { brand:"GLO Neo Boost", variante:"Pack 20", codice_aams:"8022051", alias:["glo neo boost","glo boost","glo mentol"], prezzo_pacchetto:4.30, peso_stecca_g:45, pezzi_per_stecca:10 },
  { brand:"GLO Neo Fresh", variante:"Pack 20", codice_aams:"8022052", alias:["glo neo fresh","glo fresh","glo menta"], prezzo_pacchetto:4.30, peso_stecca_g:45, pezzi_per_stecca:10 },
  { brand:"Drum Original", variante:"Busta 30g", codice_aams:"8030010", alias:["drum","drum original","drum arancione","tabacco drum"], prezzo_pacchetto:9.00, peso_stecca_g:300, pezzi_per_stecca:10 },
  { brand:"Drum Blue", variante:"Busta 30g", codice_aams:"8030011", alias:["drum blue","drum blu","drum light"], prezzo_pacchetto:9.00, peso_stecca_g:300, pezzi_per_stecca:10 },
  { brand:"Golden Virginia Original", variante:"Busta 30g", codice_aams:"8030020", alias:["golden virginia","golden virginia original","golden virginia rosse","goldenvirginia"], prezzo_pacchetto:9.30, peso_stecca_g:300, pezzi_per_stecca:10 },
  { brand:"Golden Virginia Yellow", variante:"Busta 30g", codice_aams:"8030021", alias:["golden virginia yellow","golden virginia gialle","golden virginia light"], prezzo_pacchetto:9.30, peso_stecca_g:300, pezzi_per_stecca:10 },
  { brand:"Amber Leaf", variante:"Busta 30g", codice_aams:"8030030", alias:["amber leaf","amber leaf original","amberfoglia"], prezzo_pacchetto:9.00, peso_stecca_g:300, pezzi_per_stecca:10 },
];

module.exports = { catalogo };
